[package]
name = "pkarr-cli"
version = "0.1.0"
authors = ["SeverinAlexB <severin@synonym.to>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
tokio = { version = "1.37.0", features = ["full"] }
thiserror = "1.0.49"
serde = { version = "1.0.199", features = ["derive"] }
clap = { version = "4.5.1", features = ["derive"] }
pkarr = { path = "../pkarr", features = ["async"] }
domain = {version = "0.10.1", features = ["zonefile", "bytes"]}
bytes = "1.7.1"
